name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
    inputs:
      require-current-artifact:
        description: Require the server artifact from the current workflow run
        required: false
        type: boolean
        default: false
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ZNotify/rs-sdk'

      - uses: ZNotify/test-server-action@master
        with:
          require-current-artifact: ${{ inputs.require-current-artifact || false }}

      - name: Rust Setup
        id: setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0
        with:
          shared-key: ${{ runner.os }}-cargo-${{ steps.setup.outputs.cachekey }}

      - name: Run Tests
        run: cargo test --all --verbose
        env:
          RUSTFLAGS: '--cfg mock'

